export const COUNTRY_CURRENCY_MAP: Record<string, string> = {
  "USA": "USD",
  "Canada": "CAD",
  "UK": "GBP",
  "Australia": "AUD",
  "Germany": "EUR",
  "France": "EUR",
  "Japan": "JPY",
  "India": "INR",
  "Brazil": "BRL",
  "China": "CNY",
  "Mexico": "MXN",
  "South Korea": "KRW",
  "Italy": "EUR",
  "Spain": "EUR",
  "Netherlands": "EUR",
  "Switzerland": "CHF",
  "Sweden": "SEK",
  "Norway": "NOK",
  "Denmark": "DKK",
  "Russia": "RUB",
  "South Africa": "ZAR",
  "Argentina": "ARS",
  "Turkey": "TRY",
  "Saudi Arabia": "SAR",
  "UAE": "AED",
  "Singapore": "SGD",
  "New Zealand": "NZD",
  "Thailand": "THB",
  "Vietnam": "VND",
  "Indonesia": "IDR",
  "Malaysia": "MYR",
  "Philippines": "PHP",
  "Poland": "PLN",
  "Czech Republic": "CZK",
  "Hungary": "HUF",
  "Romania": "RON",
  "Chile": "CLP",
  "Colombia": "COP",
  "Peru": "PEN",
  "Egypt": "EGP",
  "Nigeria": "NGN",
  "Kenya": "KES",
  "Pakistan": "PKR",
  "Bangladesh": "BDT"
};

export const CURRENCY_SYMBOLS: Record<string, string> = {
  "USD": "$",
  "CAD": "C$",
  "GBP": "£",
  "AUD": "A$",
  "EUR": "€",
  "JPY": "¥",
  "INR": "₹",
  "BRL": "R$",
  "CNY": "¥",
  "MXN": "$",
  "KRW": "₩",
  "CHF": "CHF",
  "SEK": "kr",
  "NOK": "kr",
  "DKK": "kr",
  "RUB": "₽",
  "ZAR": "R",
  "ARS": "$",
  "TRY": "₺",
  "SAR": "﷼",
  "AED": "د.إ",
  "SGD": "S$",
  "NZD": "NZ$",
  "THB": "฿",
  "VND": "₫",
  "IDR": "Rp",
  "MYR": "RM",
  "PHP": "₱",
  "PLN": "zł",
  "CZK": "Kč",
  "HUF": "Ft",
  "RON": "lei",
  "CLP": "$",
  "COP": "$",
  "PEN": "S/",
  "EGP": "£",
  "NGN": "₦",
  "KES": "KSh",
  "PKR": "₨",
  "BDT": "৳"
};

export const SUPPORTED_LANGUAGES: Record<string, string> = {
  "English": "English",
  "Spanish": "Español",
  "French": "Français",
  "German": "Deutsch",
  "Hindi": "हिन्दी",
  "Bengali": "বাংলা",
  "Chinese": "中文 (简体)",
  "Japanese": "日本語",
  "Korean": "한국어",
  "Portuguese": "Português",
  "Russian": "Русский",
  "Arabic": "العربية",
  "Turkish": "Türkçe",
  "Thai": "ไทย",
  "Vietnamese": "Tiếng Việt",
  "Indonesian": "Bahasa Indonesia",
  "Italian": "Italiano",
  "Dutch": "Nederlands",
  "Urdu": "اردو"
};
